export const MOVES = [
  { id: "concession-pivot", name: "The Concession Pivot",
    what: "Grant the strongest version of the objection, then redirect to the deeper point. Disarms opposition because you've shown you heard it.",
    frame: "\"That's fair, and if X were the whole story you'd be right. But the deeper issue is Y.\"",
    example: "\"You're right that wellness apps have brutal churn. If Helix were another habit tracker, that would kill it. But the retention driver here isn't habit, it's location: your air quality changes whether you open the app or not.\"" },
  { id: "diagnosis-swap", name: "The Diagnosis Swap",
    what: "Replace the surface problem with the real one. 'It's not X, it's Y' instantly reframes the entire conversation around your analysis.",
    frame: "\"This isn't a [surface] problem. It's a [root] problem.\"",
    example: "\"Slow sales at The Den isn't a pricing problem, it's a foot-traffic problem. Discounting won't fix an empty hallway.\"" },
  { id: "rule-of-three", name: "The Rule of Three",
    what: "Group points in threes. Two feels thin, four feels like a list, three feels complete. Build rhythm: short, short, long.",
    frame: "\"We did three things: A. B. And most importantly, C.\"",
    example: "\"Grading comes down to three things: centering, surfaces, and the edges nobody checks until it's too late.\"" },
  { id: "antithesis", name: "Antithesis",
    what: "Set two opposites against each other in parallel structure. The contrast does the persuading.",
    frame: "\"Not X, but Y.\" / \"X is what it costs; Y is what it's worth.\"",
    example: "\"We're not selling data. We're selling decisions.\"" },
  { id: "concrete-swap", name: "The Concrete Swap",
    what: "Replace every abstraction with a number, an image, or a person. Abstract claims wash over people; concrete ones stick.",
    frame: "Instead of \"significant growth,\" say the number. Instead of \"users,\" name one.",
    example: "\"Revenue grew from thirty-four thousand to forty-five thousand\" beats \"revenue grew significantly\" every single time." },
  { id: "steelman", name: "Steelman First",
    what: "State the opposing case better than its own advocates would, then answer it. Signals confidence and earns the right to be believed.",
    frame: "\"The best argument against this is... And here's why it still doesn't hold.\"",
    example: "\"The strongest case against buying sealed product is reprint risk, and it's real. Here's why this particular set is insulated from it.\"" },
  { id: "short-sentence", name: "The Landing Sentence",
    what: "After two or three long sentences, land a very short one. The rhythm break creates emphasis without raising your voice.",
    frame: "Long, long, then: three words.",
    example: "\"We modeled the pull rates, cross-checked the pop reports, and ran the numbers against three months of sold listings. The card is underpriced.\"" },
  { id: "question-pivot", name: "The Question Pivot",
    what: "Reject the question's frame by naming a better question. You now control what the conversation is about.",
    frame: "\"The real question isn't X. It's Y.\"",
    example: "\"The real question isn't whether the app is accurate. It's whether anyone changes their behavior because of it.\"" },
  { id: "definitional", name: "The Definitional Move",
    what: "When a debate stalls, expose that both sides mean different things by the key word. Whoever defines the term controls the argument.",
    frame: "\"Depends what you mean by [term]. If you mean A, then... If you mean B, then...\"",
    example: "\"Depends what you mean by 'moat.' If you mean technology, no. If you mean a dataset nobody else is bothering to assemble, yes.\"" },
  { id: "enumerate-collapse", name: "Enumerate, Then Collapse",
    what: "List several points, then reveal they're all one point. The collapse creates an 'aha' and makes you look like you see structure others miss.",
    frame: "\"There are three problems here... but really they're all the same problem: Z.\"",
    example: "\"Slow checkout, inventory mismatches, refund disputes: three complaints, one cause. Nothing at The Den is written down.\"" },
  { id: "callback", name: "The Callback",
    what: "Reference something said earlier, by you or by them, at the perfect later moment. Nothing signals presence and intelligence more cheaply.",
    frame: "\"Going back to what you said about X...\"",
    example: "Judge mentions risk in minute one. In minute seven: \"You asked about risk earlier. This slide is the answer.\"" },
  { id: "analogy", name: "The Load-Bearing Analogy",
    what: "Explain the unfamiliar through the familiar, then push the analogy one step further than expected. Weak analogies decorate; strong ones argue.",
    frame: "\"X is like Y. And just like Y, it has [non-obvious shared property].\"",
    example: "\"A pop report is a stock float. And just like a float, the scary number isn't what exists, it's what's still coming.\"" },
  { id: "anaphora", name: "Anaphora",
    what: "Repeat the same opening words across successive sentences. Builds momentum; the repetition becomes a drumbeat. Use sparingly, at peaks.",
    frame: "\"We tested X. We tested Y. We tested Z. Then we stopped testing and started selling.\"",
    example: "\"Every collector checks centering. Every collector checks corners. Almost nobody checks print lines, and that's where the money is.\"" },
  { id: "precision-hedge", name: "The Precise Hedge",
    what: "Hedge with exact confidence levels instead of mush. 'Probably', 'I'd put it at 70 percent', 'I'm sure of A, unsure of B'. Precise uncertainty reads as competence; vague uncertainty reads as weakness.",
    frame: "\"I'm confident about X. I'm about 70 percent on Y. Z I'd want to verify.\"",
    example: "\"The margin math is solid. The demand estimate is directional at best, and I'd want fifty more waitlist signups before trusting it.\"" },
  { id: "silence", name: "Strategic Silence",
    what: "After making your key point or asking your key question: stop. The urge to fill silence is where people talk themselves out of strong positions.",
    frame: "State the number. Ask the question. Then wait.",
    example: "\"The price is four hundred.\" Silence. The first person to speak after an anchor usually concedes." },
];
